// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: proto/iot.proto

package iot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid string `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"` // guid
}

func (x *ProjectRequest) Reset() {
	*x = ProjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRequest) ProtoMessage() {}

func (x *ProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRequest.ProtoReflect.Descriptor instead.
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type ProjectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`  // 상태코드
	Project string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"` //프로젝트
}

func (x *ProjectReply) Reset() {
	*x = ProjectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectReply) ProtoMessage() {}

func (x *ProjectReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectReply.ProtoReflect.Descriptor instead.
func (*ProjectReply) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProjectReply) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// The request message containing the user's name.
type SetFileInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid     string `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	VideoMd5 string `protobuf:"bytes,3,opt,name=videoMd5,proto3" json:"videoMd5,omitempty"`
	SubFile  string `protobuf:"bytes,4,opt,name=subFile,proto3" json:"subFile,omitempty"` // sclice
}

func (x *SetFileInfoRequest) Reset() {
	*x = SetFileInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFileInfoRequest) ProtoMessage() {}

func (x *SetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*SetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{2}
}

func (x *SetFileInfoRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *SetFileInfoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SetFileInfoRequest) GetVideoMd5() string {
	if x != nil {
		return x.VideoMd5
	}
	return ""
}

func (x *SetFileInfoRequest) GetSubFile() string {
	if x != nil {
		return x.SubFile
	}
	return ""
}

// The response message containing the greetings
type SetFileInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SetFileInfoReply) Reset() {
	*x = SetFileInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFileInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFileInfoReply) ProtoMessage() {}

func (x *SetFileInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFileInfoReply.ProtoReflect.Descriptor instead.
func (*SetFileInfoReply) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{3}
}

func (x *SetFileInfoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFindFileInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubFile string `protobuf:"bytes,1,opt,name=subFile,proto3" json:"subFile,omitempty"`
}

func (x *GetFindFileInfoRequest) Reset() {
	*x = GetFindFileInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFindFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFindFileInfoRequest) ProtoMessage() {}

func (x *GetFindFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFindFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFindFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{4}
}

func (x *GetFindFileInfoRequest) GetSubFile() string {
	if x != nil {
		return x.SubFile
	}
	return ""
}

type GetFindFileInReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid     string `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	VideoMd5 string `protobuf:"bytes,3,opt,name=videoMd5,proto3" json:"videoMd5,omitempty"`
	SubFile  string `protobuf:"bytes,4,opt,name=subFile,proto3" json:"subFile,omitempty"`
}

func (x *GetFindFileInReply) Reset() {
	*x = GetFindFileInReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFindFileInReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFindFileInReply) ProtoMessage() {}

func (x *GetFindFileInReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFindFileInReply.ProtoReflect.Descriptor instead.
func (*GetFindFileInReply) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{5}
}

func (x *GetFindFileInReply) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *GetFindFileInReply) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetFindFileInReply) GetVideoMd5() string {
	if x != nil {
		return x.VideoMd5
	}
	return ""
}

func (x *GetFindFileInReply) GetSubFile() string {
	if x != nil {
		return x.SubFile
	}
	return ""
}

type PutFileInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubFile string `protobuf:"bytes,1,opt,name=subFile,proto3" json:"subFile,omitempty"`
}

func (x *PutFileInfoRequest) Reset() {
	*x = PutFileInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileInfoRequest) ProtoMessage() {}

func (x *PutFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileInfoRequest.ProtoReflect.Descriptor instead.
func (*PutFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{6}
}

func (x *PutFileInfoRequest) GetSubFile() string {
	if x != nil {
		return x.SubFile
	}
	return ""
}

type PutFileInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubFileCount int32 `protobuf:"varint,1,opt,name=subFileCount,proto3" json:"subFileCount,omitempty"`
}

func (x *PutFileInfoReply) Reset() {
	*x = PutFileInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutFileInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileInfoReply) ProtoMessage() {}

func (x *PutFileInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileInfoReply.ProtoReflect.Descriptor instead.
func (*PutFileInfoReply) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{7}
}

func (x *PutFileInfoReply) GetSubFileCount() int32 {
	if x != nil {
		return x.SubFileCount
	}
	return 0
}

type RemoveFileInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoMd5 string `protobuf:"bytes,1,opt,name=videoMd5,proto3" json:"videoMd5,omitempty"`
}

func (x *RemoveFileInfoRequest) Reset() {
	*x = RemoveFileInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileInfoRequest) ProtoMessage() {}

func (x *RemoveFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileInfoRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveFileInfoRequest) GetVideoMd5() string {
	if x != nil {
		return x.VideoMd5
	}
	return ""
}

type RemoveFileInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RemoveFileInfoReply) Reset() {
	*x = RemoveFileInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFileInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileInfoReply) ProtoMessage() {}

func (x *RemoveFileInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileInfoReply.ProtoReflect.Descriptor instead.
func (*RemoveFileInfoReply) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveFileInfoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubFileCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoMd5 string `protobuf:"bytes,1,opt,name=videoMd5,proto3" json:"videoMd5,omitempty"`
}

func (x *SubFileCountRequest) Reset() {
	*x = SubFileCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubFileCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubFileCountRequest) ProtoMessage() {}

func (x *SubFileCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubFileCountRequest.ProtoReflect.Descriptor instead.
func (*SubFileCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{10}
}

func (x *SubFileCountRequest) GetVideoMd5() string {
	if x != nil {
		return x.VideoMd5
	}
	return ""
}

type SubFileCountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message int32 `protobuf:"varint,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SubFileCountReply) Reset() {
	*x = SubFileCountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubFileCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubFileCountReply) ProtoMessage() {}

func (x *SubFileCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubFileCountReply.ProtoReflect.Descriptor instead.
func (*SubFileCountReply) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{11}
}

func (x *SubFileCountReply) GetMessage() int32 {
	if x != nil {
		return x.Message
	}
	return 0
}

var File_proto_iot_proto protoreflect.FileDescriptor

var file_proto_iot_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x22, 0x40,
	0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x22, 0x7a, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d,
	0x64, 0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d,
	0x64, 0x35, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x2c, 0x0a, 0x10,
	0x53, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x7a,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x64, 0x35,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x64, 0x35,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x50, 0x75,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x50, 0x75,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22,
	0x0a, 0x0c, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x33, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x4d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x4d, 0x64, 0x35, 0x22, 0x2f, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x31, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x64, 0x35, 0x22, 0x2d, 0x0a, 0x11, 0x53,
	0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xb0, 0x03, 0x0a, 0x07, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x53,
	0x75, 0x62, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x0b, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x46, 0x69, 0x6c, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75,
	0x62, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x46, 0x69, 0x6c,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x23, 0x5a,
	0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x66, 0x74,
	0x6b, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69,
	0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_iot_proto_rawDescOnce sync.Once
	file_proto_iot_proto_rawDescData = file_proto_iot_proto_rawDesc
)

func file_proto_iot_proto_rawDescGZIP() []byte {
	file_proto_iot_proto_rawDescOnce.Do(func() {
		file_proto_iot_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_iot_proto_rawDescData)
	})
	return file_proto_iot_proto_rawDescData
}

var file_proto_iot_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_iot_proto_goTypes = []interface{}{
	(*ProjectRequest)(nil),         // 0: proto.ProjectRequest
	(*ProjectReply)(nil),           // 1: proto.ProjectReply
	(*SetFileInfoRequest)(nil),     // 2: proto.SetFileInfoRequest
	(*SetFileInfoReply)(nil),       // 3: proto.SetFileInfoReply
	(*GetFindFileInfoRequest)(nil), // 4: proto.GetFindFileInfoRequest
	(*GetFindFileInReply)(nil),     // 5: proto.GetFindFileInReply
	(*PutFileInfoRequest)(nil),     // 6: proto.PutFileInfoRequest
	(*PutFileInfoReply)(nil),       // 7: proto.PutFileInfoReply
	(*RemoveFileInfoRequest)(nil),  // 8: proto.RemoveFileInfoRequest
	(*RemoveFileInfoReply)(nil),    // 9: proto.RemoveFileInfoReply
	(*SubFileCountRequest)(nil),    // 10: proto.SubFileCountRequest
	(*SubFileCountReply)(nil),      // 11: proto.SubFileCountReply
}
var file_proto_iot_proto_depIdxs = []int32{
	0,  // 0: proto.Greeter.GetProject:input_type -> proto.ProjectRequest
	2,  // 1: proto.Greeter.SetFileInfo:input_type -> proto.SetFileInfoRequest
	4,  // 2: proto.Greeter.FindSubFile:input_type -> proto.GetFindFileInfoRequest
	6,  // 3: proto.Greeter.PutFileInfo:input_type -> proto.PutFileInfoRequest
	8,  // 4: proto.Greeter.DeleteFileInfo:input_type -> proto.RemoveFileInfoRequest
	10, // 5: proto.Greeter.SubFileCount:input_type -> proto.SubFileCountRequest
	1,  // 6: proto.Greeter.GetProject:output_type -> proto.ProjectReply
	3,  // 7: proto.Greeter.SetFileInfo:output_type -> proto.SetFileInfoReply
	5,  // 8: proto.Greeter.FindSubFile:output_type -> proto.GetFindFileInReply
	7,  // 9: proto.Greeter.PutFileInfo:output_type -> proto.PutFileInfoReply
	9,  // 10: proto.Greeter.DeleteFileInfo:output_type -> proto.RemoveFileInfoReply
	11, // 11: proto.Greeter.SubFileCount:output_type -> proto.SubFileCountReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_iot_proto_init() }
func file_proto_iot_proto_init() {
	if File_proto_iot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_iot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFileInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFileInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFindFileInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFindFileInReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutFileInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutFileInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFileInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFileInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubFileCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubFileCountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_iot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iot_proto_goTypes,
		DependencyIndexes: file_proto_iot_proto_depIdxs,
		MessageInfos:      file_proto_iot_proto_msgTypes,
	}.Build()
	File_proto_iot_proto = out.File
	file_proto_iot_proto_rawDesc = nil
	file_proto_iot_proto_goTypes = nil
	file_proto_iot_proto_depIdxs = nil
}
